### ISSUE TITLE
Sort error

### ISSUE THREAD

**Issue by k1ngf15h3r** [Perlkonig/grav-skeleton-knowledge-base#1]
I really like to test this awesome theme, but I can not get it runnig.

I installed grav+admin plugin first, than added the knowledge-base theme and at least I replaced config and pages content with the skeleton content. but everytime I want to open my site I got:

`0 - The sort filter only works with arrays or "Traversable", got "NULL" in "default.html.twig" at line 1.`

Any idea how to fix this? Is there a complete skeleton avaiable soon?

**Comment by Perlkonig** [comment]
I'm finally building the skeleton and having the same error. Which is weird because the demo site is fine. Will work this out today and get the skeleton uploaded hopefully this weekend.

**Comment by k1ngf15h3r** [comment]
Thank you for the Information. I will look into it when the skeleton is
ready :)

Am 05.11.2016 4:52 nachm. schrieb "Aaron Dalton" notifications@github.com:

**Comment by Perlkonig** [comment]
The problem was that `count-views` wasn't being properly installed. I just released a fully functioning skeleton. Reopen if it's still broken for you. Thanks!

**Comment by k1ngf15h3r** [comment]
Works :)  but authors Page is empty. Is this correct  when I run skeleton without change? Which contact Form did you use in your Demo?

**Comment by Perlkonig** [comment]
The [Authors page](https://perlkonig.com/knowledge-base/taxonomy?name=author) Should list the four authors. Can you send me a screen capture of what you're seeing?

[No built-in contact page.](https://perlkonig.com/knowledge-base/contact) Either use the built-in Form plugin or go with something like the recaptchaContact plugin (easiest to just drop into a page).

**Comment by k1ngf15h3r** [comment]
This is what I see. 

[https://wiki.hagels.net/taxonomy?name=author](https://wiki.hagels.net/taxonomy?name=author)

![2016-11-05 23_52_16-by taxonomy _ knowledge base](https://cloud.githubusercontent.com/assets/1043669/20034115/0f9202d6-a3b3-11e6-9ab8-b9a27f4a417e.png)

**Comment by Perlkonig** [comment]
Thanks for the link. So none of the taxonomies are working. Hrm...

**Comment by Perlkonig** [comment]
I just extracted the binary into a clean folder [and it appears to be working](https://perlkonig.com/grav/taxonomy?name=author). Have you double checked that all the pages are there?

**Comment by k1ngf15h3r** [comment]
the pages are there, all three default author pages ...

**Comment by k1ngf15h3r** [comment]
do I need the taxonomylist plugin? this should be missing in the skeleton. which route does it need?

**Comment by Perlkonig** [comment]
You do not need the taxonomylist plugin. By pages I mean user/pages/01.home/*.

**Comment by k1ngf15h3r** [comment]
Yes they are are there. 

![screenshot_20161106-011056](https://cloud.githubusercontent.com/assets/1043669/20034424/010ca7b0-a3be-11e6-8a16-a10a8b09d647.png)

**Comment by Perlkonig** [comment]
Gotta love JuiceSSH 😄 

If you don't mind, can you please zip up your entire `user` folder and send it to me? I need to see if I can duplicate this. Thanks!

**Comment by k1ngf15h3r** [comment]
Yeah JuiceSSH is great for administrtion on mobile ;)

Hope this help you to duplicate the error : [https://github.com/k1ngf15h3r/kb-dev](https://github.com/k1ngf15h3r/kb-dev)

**Comment by k1ngf15h3r** [comment]
Did a fresh install of the skeleton this morning but same result. Does the git content help you?

**Comment by Perlkonig** [comment]
According to what you posted, not all the plugins are installed. Once I installed them all, it worked fine.

I just updated the README. Regardless of how you download the skeleton, you need to run `bin/grav install` to get all the dependencies installed. Try again, please, and let me know.

**Comment by k1ngf15h3r** [comment]
Getting this output when doing `bin/grav install` result is the same as before -.-

```
[root@mail wiki]# bin/grav install
Installing vendor dependencies
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
    Skipped installation of bin bin/minifycss for package matthiasmullie/minify: file not found in package
    Skipped installation of bin bin/minifyjs for package matthiasmullie/minify: file not found in package
Cloning Bits
============
/var/www/html/wiki/user/plugins/error already exists, skipping...
/var/www/html/wiki/user/plugins/problems already exists, skipping...
/var/www/html/wiki/user/plugins/relatedpages already exists, skipping...
/var/www/html/wiki/user/plugins/simplesearch already exists, skipping...
/var/www/html/wiki/user/plugins/readingtime already exists, skipping...
/var/www/html/wiki/user/plugins/count-views already exists, skipping...
/var/www/html/wiki/user/themes/knowledge-base already exists, skipping...
```

**Comment by k1ngf15h3r** [comment]
Can you tell me which plugins were missing?

Am 07.11.2016 14:11 schrieb "Aaron Dalton" notifications@github.com:

**Comment by Perlkonig** [comment]
I'm not sure what to say. I just now did the following steps:
1. Download the binary ZIP from the latest release.
2. Unzipped into `grav` folder.
3. From the `grav` folder, I typed `bin/grav install` and got the same output you did.
4. (Just for me and because of my setup, I did a `chgrp`.)
5. [It works](https://perlkonig.com/grav/).

As for the missing plugins, go to your repo and you'll see. Even the theme was missing from what you sent. Probably just an issue with `.gitignore` files ore something. Regardless, it keeps installing fine for me.

**Comment by k1ngf15h3r** [comment]
I will test it on my offline system at home. Maybe it is something on my online webserver. Could it be something with nginx? or with the variable base_url?

**Comment by Perlkonig** [comment]
I don't think it's a problem with the server because when I downloaded your repo and installed the theme, I got the same error. It wasn't until all the plugins were properly installed that things started working. Can you just zip up the `user` folder (to avoid issues with `.gitignore` files) and post it?

**Comment by k1ngf15h3r** [comment]
Here is the zip of the user folder
[user.zip](http://nas.hagels.net:8080/share.cgi?ssid=0WDfSA3)

**Comment by Perlkonig** [comment]
Thanks! I installed that on the dev server and [everything is working as expected.](https://perlkonig.com/grav/).

**Comment by k1ngf15h3r** [comment]
hm that is strange. only thing that is other on my setup is that I run it not in a subfolder, but this could not be the problem. will be at home in an hour and install it on my arch linux.

**Comment by Perlkonig** [comment]
Best of luck. Let me know.

**Comment by k1ngf15h3r** [comment]
If I hardcode the taxname in the `taxonomy.html.twig` it works 😆 

```
{% block content %}
    {% set taxname = 'author' %}
    {% set taxval = uri.query('val') %}
    {% if taxname %}
        {% if taxname == 'category' %}
```

[https://wiki.hagels.net/taxonomy?name=author](https://wiki.hagels.net/taxonomy?name=author)

**Comment by Perlkonig** [comment]
Then maybe your server is doing something with the query string? `uri.query` is a Grav built-in function for extracting parameters from the query string (the part of the URL after the `?`).

**Comment by k1ngf15h3r** [comment]
Will check this at home

**Comment by k1ngf15h3r** [comment]
Do you use nginx or apache? If nginx can you show me your conf?

**Comment by k1ngf15h3r** [comment]
Solved the problem :) 

Added index.php?$query_string at the end of the try_files Option in my nginx conf ;)

**Comment by Perlkonig** [comment]
I use Apache. I have no experience with nginx. Glad you got it working!

**Comment by k1ngf15h3r** [comment]
Thank you for your help and patience

**Comment by Perlkonig** [comment]
Au plaisir.
