### ISSUE TITLE
Installation doesn't work as described.

### ISSUE THREAD

**Issue by davidcsonka** [Perlkonig/grav-skeleton-knowledge-base#11]
Installing Clean
- Download the zip file from the latest release and unzip it somewhere reachable by your webserver.
- From that root folder, type bin/grav install to install dependencies.
- You're good to go.

-- Followed these steps
bin/grav: No such file or directory
sudo: bin/grav: command not found

**Comment by Perlkonig** [comment]
I just confirmed that the zip file is indeed complete. You have to run those commands from the extracted `grav` folder. I'll see if I can make the docs more explicit.
