### ISSUE TITLE
can u offer more page templates?

### ISSUE THREAD

**Issue by Maclaon** [Perlkonig/grav-skeleton-knowledge-base#12]
can u offer more page templates in this theme? may be u can make page templates editable on github or with admin plugin on grav?

**Comment by Perlkonig** [comment]
What sort of templates do you feel you're missing?

There's nothing stopping you from editing the existing templates, even through the admin interface. That said, I don't use the admin interface, so if there's some impediment, let me know.

**Comment by Maclaon** [comment]
yeah, when i figure it out template exists in /user/themes, i can edit more templates by myself！this is powerful! thks~
