### ISSUE TITLE
Bad date formats bring down the entire site

### ISSUE THREAD

**Issue by axcodeplex** [Perlkonig/grav-skeleton-knowledge-base#14]
Creating an item.md like this:

---
title: New Content Example
date: 08-21-2018
taxonomy:
    category: [New Category 42]
    tag: []
    author: Foo
---

Note the reversal of the month/day. The format above will bring the site down with the following error:

Server Error
Sorry, something went terribly wrong!
0 - DateTime::__construct(): Failed to parse time string (08-21-2018) at position 0 (0): Unexpected character

**Comment by Perlkonig** [comment]
This isn't an issue with the theme but with Grav itself. If you change the dashes to slashes, it works fine. [Here's the doc page that talks about it.](https://learn.getgrav.org/content/headers#date) I agree that Grav should handle unambiguous cases like this more gracefully. Maybe I'll see if I can do a PR.

**Comment by axcodeplex** [comment]
Ah good call, missed that, sorry. Keep up the good work!
