### ISSUE TITLE
Can't get Simple search to work

### ISSUE THREAD

**Issue by awrog** [Perlkonig/grav-skeleton-knowledge-base#2]
Clean install from latest skeleton.
All plugins up-to-date and activated.
Cache emptied.
Whatever I search for, no result.

What could be the problem?
You can try here:  http://www.websitecoder.nl/grav

**Comment by Perlkonig** [comment]
How odd. [It works on the demo.](https://perlkonig.com/knowledge-base/search/query:interpretaris). I'd have to see the entire user folder so I can replicate. Can you zip the user folder up and share it with me?

**Comment by awrog** [comment]
attached
[user.zip](https://github.com/Perlkonig/grav-skeleton-knowledge-base/files/609530/user.zip)

**Comment by awrog** [comment]
Perlkonig, looks lies the problem lies [here](
https://github.com/getgrav/grav-plugin-simplesearch/issues/48)

When I remove blog from the filter it works.

Any chance for an updated skeleton?

**Comment by Perlkonig** [comment]
Fixed. New version released. Let me know if you have other problems.

**Comment by domsson** [comment]
I still ran into this issue today and had to remove the line ` - category: blog` in order to get the search to work. Is it possible we have a regression?

**Comment by Perlkonig** [comment]
I just did a clean install of the skeleton zip and everything worked fine.

**Comment by domsson** [comment]
Hm, maybe the `install` or `upgrade`/`update` commands would cause the file to be overwritten with the default from the repo/sources? Because I also simply unzipped the skeleton file and the `blog` filter was in there, causing the issue. Anyway, removing the line fixes the issue, apparently.

**Comment by Perlkonig** [comment]
Hrm, I guess I didn't do the `bin/grav install` step. I just unzipped it. I'll poke around.

**Comment by Perlkonig** [comment]
Nope. I can't replicate. I started fresh, downloaded the latest zip file, unzipped it, and checked the config. It's clean. Then I ran `bin/grav install` and then checked again. The config is clean. I checked the repo, and indeed the repo has a clean `config/plugins/simplesearch.yaml`. So I'm not sure what's happening.
