### ISSUE TITLE
Skeleton.

### ISSUE THREAD

**Issue by hifall** [Perlkonig/grav-skeleton-knowledge-base#4]
Hi,

The repo doesn't seems to contain grav. Is this supposed to be a skeleton package?

Thanks!

**Comment by Perlkonig** [comment]
If you go to the releases tab, you'll see a ZIP file attached to the release. Download that. I haven't kept the skeleton up to do date. It's a bit of a pain. So once you unzip it you need to do a `bin/gpm self-upgrade` and `bin/gpm update` to bring everything up to date. I'll try to get an updated skeleton uploaded soon.
