### ISSUE TITLE
Taxonomy page fails on fresh install

### ISSUE THREAD

**Issue by markfox1** [Perlkonig/grav-skeleton-knowledge-base#6]
After a fresh install of GRAV and grav-skeleton-knowledge-base, the taxonomy page fails to do anything useful with the name attribute. Whether it is set to category, tag, or author, it just displays the list of taxonomies.

**Comment by Perlkonig** [comment]
The skeleton isn't up to date. Be sure to do an update. Please post a screen capture of what you're getting. Thanks!

**Comment by Perlkonig** [comment]
Reopen if you still have issues after updating.
