### ISSUE TITLE
Sidebar Popular articles not working [Solved]

### ISSUE THREAD

**Issue by awrog** [Perlkonig/grav-skeleton-knowledge-base#7]
Love this skeleton!!

It looks like the sidebar **Popular Articles** is not working
Installed th KB Skeleton (a fresh updated skeleton would be great by the way :-) )
Updated all plugins
Added some data
The sidebar ends up 'empty' (= it has entries but no links)
![screenshot - 6_22_2017 10_39_57 am](https://user-images.githubusercontent.com/12153667/27424974-2aa1e95a-5737-11e7-8c81-36c650c21c93.png)

Compatibility-issues with the Count Views plugin?
Quote from the Count View [documentation](https://github.com/perlkonig/grav-plugin-count-views):

> The full view count data is dumped as an associative array (i.e., route => count) into the Twig variable viewcounts. To support backwards compatibility, the counts are also still dumped into the config.plugins.count-views.counts namespace, but this is now officially deprecated and will be removed in a future major release.

**Comment by awrog** [comment]
Found the cause: the /user/data/count-views.yaml contained entries to articles that no longer exist.
It looks like renaming the foldername or deleting a page is not picked up by the Count Views-plugin!

**Comment by Perlkonig** [comment]
Thanks, @awrog. I'll still double-check the code. Only existing articles should appear in the sidebar.

**Comment by Perlkonig** [comment]
Just released an update to the theme (v1.3.3) that fixes this issue.

**Comment by Perlkonig** [comment]
Updating the skeleton is a bit of a pain. I'll do what I can this weekend.

**Comment by awrog** [comment]
Thanks!

 @Perlkonig interesting CV you've got, I also do some music engraving (Lilypond))

**Comment by Perlkonig** [comment]
Lilypond is the bomb. I wish I did more with music nowadays.
