### ISSUE TITLE
bin/grav install fails due to Symfony parse error

### ISSUE THREAD

**Issue by domsson** [Perlkonig/grav-skeleton-knowledge-base#9]
Thank you for your skeleton! Sadly I'm running into a problem.

After setting up a server on a RaspberryPi (running php 5.6.3) and unzipping your skeleton, I tried running `bin/grav install` as per your README. This gives me an error:

    [Symfony\Component\Yaml\Exception\ParseException]
    Unable to parse at line 50 (near "count-views").

I haven't done much research yet, but maybe this is due to [this rather old bug in Symfony](https://github.com/symfony/symfony/issues/17116)? If so, maybe you could point me to what files it is actually trying to parse so I could try the workaround suggested over there. Or maybe there is a manual way of doing whatever `bin/grav install` is trying to do?

Cheers!

**Comment by Perlkonig** [comment]
Ugh. I screwed something up when creating the zip file. Edit the `.dependencies` file, go to line 50, and add the missing colon. I will fix this as soon as I can in the repo.

**Comment by Perlkonig** [comment]
New release published.
